CREATE TABLE IF NOT EXISTS plagiarism_jobs (
    id BIGINT PRIMARY KEY,
    contest_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    detector VARCHAR(32) NOT NULL,
    options_json TEXT,
    minimum_similarity DECIMAL(6,4) NOT NULL DEFAULT 0.5500,
    include_ai_analysis TINYINT(1) NOT NULL DEFAULT 1,
    total_submissions INT NOT NULL DEFAULT 0,
    total_pairs INT NOT NULL DEFAULT 0,
    high_risk_pairs INT NOT NULL DEFAULT 0,
    error_message VARCHAR(500),
    created_by BIGINT NOT NULL,
    started_at DATETIME(3),
    completed_at DATETIME(3),
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_plagiarism_jobs_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_plagiarism_jobs_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_plagiarism_jobs_contest_status (contest_id, status, created_at),
    INDEX idx_plagiarism_jobs_created_by (created_by, created_at)
);

CREATE TABLE IF NOT EXISTS plagiarism_job_submissions (
    id BIGINT PRIMARY KEY,
    job_id BIGINT NOT NULL,
    contest_id BIGINT NOT NULL,
    contest_problem_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    submission_id BIGINT NOT NULL,
    contest_participant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    language VARCHAR(32) NOT NULL,
    account_snapshot VARCHAR(80) NOT NULL,
    display_name_snapshot VARCHAR(120) NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    code_chars INT NOT NULL,
    included TINYINT(1) NOT NULL DEFAULT 1,
    exclude_reason VARCHAR(240),
    created_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_plagiarism_job_submissions_job FOREIGN KEY (job_id) REFERENCES plagiarism_jobs(id),
    CONSTRAINT fk_plagiarism_job_submissions_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_plagiarism_job_submissions_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT fk_plagiarism_job_submissions_participant FOREIGN KEY (contest_participant_id) REFERENCES contest_participants(id),
    UNIQUE KEY uk_plagiarism_job_submission (job_id, submission_id),
    INDEX idx_plagiarism_job_submissions_group (job_id, contest_problem_id, language),
    INDEX idx_plagiarism_job_submissions_user (job_id, user_id)
);

CREATE TABLE IF NOT EXISTS plagiarism_pairs (
    id BIGINT PRIMARY KEY,
    job_id BIGINT NOT NULL,
    contest_id BIGINT NOT NULL,
    contest_problem_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    language VARCHAR(32) NOT NULL,
    left_job_submission_id BIGINT NOT NULL,
    right_job_submission_id BIGINT NOT NULL,
    left_submission_id BIGINT NOT NULL,
    right_submission_id BIGINT NOT NULL,
    left_user_id BIGINT NOT NULL,
    right_user_id BIGINT NOT NULL,
    left_participant_id BIGINT NOT NULL,
    right_participant_id BIGINT NOT NULL,
    similarity DECIMAL(6,4) NOT NULL,
    maximal_similarity DECIMAL(6,4) NOT NULL,
    minimal_similarity DECIMAL(6,4) NOT NULL,
    matched_tokens INT NOT NULL DEFAULT 0,
    risk_level VARCHAR(32) NOT NULL,
    review_status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    teacher_note VARCHAR(500),
    reviewed_by BIGINT,
    reviewed_at DATETIME(3),
    ai_status VARCHAR(32) NOT NULL DEFAULT 'SKIPPED',
    ai_summary VARCHAR(500),
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_plagiarism_pairs_job FOREIGN KEY (job_id) REFERENCES plagiarism_jobs(id),
    CONSTRAINT fk_plagiarism_pairs_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_plagiarism_pairs_problem FOREIGN KEY (contest_problem_id) REFERENCES contest_problems(id),
    CONSTRAINT fk_plagiarism_pairs_left_submission FOREIGN KEY (left_submission_id) REFERENCES submissions(id),
    CONSTRAINT fk_plagiarism_pairs_right_submission FOREIGN KEY (right_submission_id) REFERENCES submissions(id),
    INDEX idx_plagiarism_pairs_job_similarity (job_id, similarity),
    INDEX idx_plagiarism_pairs_job_risk (job_id, risk_level, review_status),
    INDEX idx_plagiarism_pairs_problem (contest_id, contest_problem_id, language, similarity)
);

CREATE TABLE IF NOT EXISTS plagiarism_fragments (
    id BIGINT PRIMARY KEY,
    pair_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    sequence_no INT NOT NULL,
    left_start_token INT NOT NULL,
    right_start_token INT NOT NULL,
    token_length INT NOT NULL,
    left_excerpt TEXT,
    right_excerpt TEXT,
    created_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_plagiarism_fragments_pair FOREIGN KEY (pair_id) REFERENCES plagiarism_pairs(id),
    CONSTRAINT fk_plagiarism_fragments_job FOREIGN KEY (job_id) REFERENCES plagiarism_jobs(id),
    INDEX idx_plagiarism_fragments_pair (pair_id, sequence_no)
);

CREATE TABLE IF NOT EXISTS plagiarism_ai_analyses (
    id BIGINT PRIMARY KEY,
    pair_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    provider VARCHAR(80),
    model VARCHAR(120),
    prompt_tokens BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    analysis MEDIUMTEXT,
    error_message VARCHAR(500),
    trace_id VARCHAR(80),
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_plagiarism_ai_analyses_pair FOREIGN KEY (pair_id) REFERENCES plagiarism_pairs(id),
    CONSTRAINT fk_plagiarism_ai_analyses_job FOREIGN KEY (job_id) REFERENCES plagiarism_jobs(id),
    INDEX idx_plagiarism_ai_analyses_pair (pair_id, created_at),
    INDEX idx_plagiarism_ai_analyses_job_status (job_id, status)
);
