CREATE TABLE contest_resolver_sessions (
    id BIGINT PRIMARY KEY,
    contest_id BIGINT NOT NULL,
    contest_run_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    view_type VARCHAR(32) NOT NULL,
    freeze_snapshot_id BIGINT NULL,
    final_snapshot_id BIGINT NULL,
    step_count INT NOT NULL DEFAULT 0,
    checksum VARCHAR(128) NOT NULL,
    created_by BIGINT NOT NULL,
    published_at DATETIME(3) NULL,
    archived_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_resolver_sessions_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_resolver_sessions_run FOREIGN KEY (contest_run_id) REFERENCES contest_runs(id),
    CONSTRAINT fk_resolver_sessions_freeze_snapshot FOREIGN KEY (freeze_snapshot_id) REFERENCES contest_scoreboard_snapshots(id),
    CONSTRAINT fk_resolver_sessions_final_snapshot FOREIGN KEY (final_snapshot_id) REFERENCES contest_scoreboard_snapshots(id),
    CONSTRAINT fk_resolver_sessions_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_resolver_sessions_run_status_created (contest_run_id, status, created_at),
    INDEX idx_resolver_sessions_contest_run (contest_id, contest_run_id)
);

CREATE TABLE contest_resolver_steps (
    id BIGINT PRIMARY KEY,
    resolver_session_id BIGINT NOT NULL,
    contest_id BIGINT NOT NULL,
    contest_run_id BIGINT NOT NULL,
    step_order INT NOT NULL,
    step_type VARCHAR(32) NOT NULL,
    participant_id BIGINT NULL,
    contest_problem_id BIGINT NULL,
    submission_id BIGINT NULL,
    payload_json TEXT NOT NULL,
    scoreboard_json MEDIUMTEXT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_resolver_steps_session FOREIGN KEY (resolver_session_id) REFERENCES contest_resolver_sessions(id),
    CONSTRAINT fk_resolver_steps_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_resolver_steps_run FOREIGN KEY (contest_run_id) REFERENCES contest_runs(id),
    CONSTRAINT fk_resolver_steps_participant FOREIGN KEY (participant_id) REFERENCES contest_participants(id),
    CONSTRAINT fk_resolver_steps_problem FOREIGN KEY (contest_problem_id) REFERENCES contest_problems(id),
    CONSTRAINT fk_resolver_steps_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    UNIQUE KEY uk_resolver_steps_order (resolver_session_id, step_order),
    INDEX idx_resolver_steps_run_order (contest_run_id, resolver_session_id, step_order),
    INDEX idx_resolver_steps_submission (submission_id)
);
