CREATE TABLE contest_postmortem_reports (
    id BIGINT PRIMARY KEY,
    contest_id BIGINT NOT NULL,
    contest_run_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    ai_status VARCHAR(32) NOT NULL,
    generated_by BIGINT NOT NULL,
    statistics_json MEDIUMTEXT NOT NULL,
    ai_markdown MEDIUMTEXT NULL,
    ai_provider VARCHAR(80) NULL,
    ai_model VARCHAR(120) NULL,
    prompt_tokens BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    error_message VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    completed_at DATETIME(3) NULL,
    CONSTRAINT fk_postmortem_reports_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_postmortem_reports_run FOREIGN KEY (contest_run_id) REFERENCES contest_runs(id),
    CONSTRAINT fk_postmortem_reports_generated_by FOREIGN KEY (generated_by) REFERENCES users(id),
    INDEX idx_postmortem_reports_run_created (contest_run_id, created_at),
    INDEX idx_postmortem_reports_status (contest_run_id, status, ai_status),
    INDEX idx_postmortem_reports_generated_by (generated_by, created_at)
);
