CREATE TABLE contest_student_postmortem_reports (
    id BIGINT PRIMARY KEY,
    contest_id BIGINT NOT NULL,
    contest_run_id BIGINT NOT NULL,
    contest_participant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    ai_status VARCHAR(32) NOT NULL,
    generated_by BIGINT NOT NULL,
    statistics_json MEDIUMTEXT NOT NULL,
    ai_markdown MEDIUMTEXT NULL,
    practice_suggestions_json MEDIUMTEXT NULL,
    ai_provider VARCHAR(80) NULL,
    ai_model VARCHAR(120) NULL,
    prompt_tokens BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    error_message VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    completed_at DATETIME(3) NULL,
    CONSTRAINT fk_student_postmortem_reports_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_student_postmortem_reports_run FOREIGN KEY (contest_run_id) REFERENCES contest_runs(id),
    CONSTRAINT fk_student_postmortem_reports_participant FOREIGN KEY (contest_participant_id) REFERENCES contest_participants(id),
    CONSTRAINT fk_student_postmortem_reports_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_student_postmortem_reports_generated_by FOREIGN KEY (generated_by) REFERENCES users(id),
    INDEX idx_student_postmortem_reports_user_run (user_id, contest_run_id, created_at),
    INDEX idx_student_postmortem_reports_run_created (contest_run_id, created_at),
    INDEX idx_student_postmortem_reports_participant (contest_participant_id, created_at),
    INDEX idx_student_postmortem_reports_status (contest_run_id, status, ai_status)
);

CREATE TABLE contest_student_postmortem_weakness_candidates (
    id BIGINT PRIMARY KEY,
    report_id BIGINT NOT NULL,
    contest_id BIGINT NOT NULL,
    contest_run_id BIGINT NOT NULL,
    contest_participant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    knowledge_node VARCHAR(160) NOT NULL,
    symptom VARCHAR(500) NOT NULL,
    tags_json TEXT NULL,
    evidence_json MEDIUMTEXT NULL,
    confidence DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
    memory_id BIGINT NULL,
    weakness_id BIGINT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    decided_at DATETIME(3) NULL,
    CONSTRAINT fk_student_postmortem_candidates_report FOREIGN KEY (report_id) REFERENCES contest_student_postmortem_reports(id),
    CONSTRAINT fk_student_postmortem_candidates_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_student_postmortem_candidates_run FOREIGN KEY (contest_run_id) REFERENCES contest_runs(id),
    CONSTRAINT fk_student_postmortem_candidates_participant FOREIGN KEY (contest_participant_id) REFERENCES contest_participants(id),
    CONSTRAINT fk_student_postmortem_candidates_user FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_student_postmortem_candidates_report (report_id, status),
    INDEX idx_student_postmortem_candidates_user_status (user_id, status, updated_at),
    INDEX idx_student_postmortem_candidates_run (contest_run_id, status)
);
