CREATE TABLE IF NOT EXISTS submission_request_fingerprints (
    id BIGINT PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    contest_id BIGINT NULL,
    contest_run_id BIGINT NULL,
    contest_participant_id BIGINT NULL,
    user_id BIGINT NOT NULL,
    ip_hash VARCHAR(64),
    ip_prefix VARCHAR(80),
    user_agent_hash VARCHAR(64),
    user_agent_summary VARCHAR(160),
    created_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_submission_request_fingerprints_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT fk_submission_request_fingerprints_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_submission_request_fingerprints_run FOREIGN KEY (contest_run_id) REFERENCES contest_runs(id),
    CONSTRAINT fk_submission_request_fingerprints_participant FOREIGN KEY (contest_participant_id) REFERENCES contest_participants(id),
    CONSTRAINT fk_submission_request_fingerprints_user FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE KEY uk_submission_request_fingerprints_submission (submission_id),
    INDEX idx_submission_fingerprints_run_ip (contest_run_id, ip_hash, created_at),
    INDEX idx_submission_fingerprints_run_ua (contest_run_id, user_agent_hash, created_at),
    INDEX idx_submission_fingerprints_participant (contest_run_id, contest_participant_id, created_at),
    INDEX idx_submission_fingerprints_user (user_id, created_at)
);

CREATE TABLE IF NOT EXISTS contest_fairness_alerts (
    id BIGINT PRIMARY KEY,
    contest_id BIGINT NOT NULL,
    contest_run_id BIGINT NOT NULL,
    alert_type VARCHAR(48) NOT NULL,
    severity VARCHAR(24) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
    primary_participant_id BIGINT NULL,
    secondary_participant_id BIGINT NULL,
    plagiarism_pair_id BIGINT NULL,
    evidence_json MEDIUMTEXT,
    teacher_note VARCHAR(500),
    reviewed_by BIGINT,
    reviewed_at DATETIME(3),
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_contest_fairness_alerts_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_contest_fairness_alerts_run FOREIGN KEY (contest_run_id) REFERENCES contest_runs(id),
    CONSTRAINT fk_contest_fairness_alerts_primary_participant FOREIGN KEY (primary_participant_id) REFERENCES contest_participants(id),
    CONSTRAINT fk_contest_fairness_alerts_secondary_participant FOREIGN KEY (secondary_participant_id) REFERENCES contest_participants(id),
    CONSTRAINT fk_contest_fairness_alerts_pair FOREIGN KEY (plagiarism_pair_id) REFERENCES plagiarism_pairs(id),
    CONSTRAINT fk_contest_fairness_alerts_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id),
    INDEX idx_fairness_alerts_run_status (contest_run_id, status, severity, created_at),
    INDEX idx_fairness_alerts_run_type (contest_run_id, alert_type, severity),
    INDEX idx_fairness_alerts_pair (plagiarism_pair_id),
    INDEX idx_fairness_alerts_primary (contest_run_id, primary_participant_id),
    INDEX idx_fairness_alerts_secondary (contest_run_id, secondary_participant_id)
);
