CREATE TABLE IF NOT EXISTS group_training_reports (
    id BIGINT PRIMARY KEY,
    contest_id BIGINT NOT NULL,
    contest_run_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    subgroup_id BIGINT NULL,
    scope_key VARCHAR(80) NOT NULL,
    generated_by BIGINT NOT NULL,
    contest_title_snapshot VARCHAR(200) NOT NULL,
    run_title_snapshot VARCHAR(160) NOT NULL,
    group_name_snapshot VARCHAR(160) NOT NULL,
    subgroup_name_snapshot VARCHAR(160),
    mode_snapshot VARCHAR(16) NOT NULL,
    member_count INT NOT NULL DEFAULT 0,
    participant_count INT NOT NULL DEFAULT 0,
    submission_count INT NOT NULL DEFAULT 0,
    statistics_json MEDIUMTEXT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_group_training_reports_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_group_training_reports_run FOREIGN KEY (contest_run_id) REFERENCES contest_runs(id),
    CONSTRAINT fk_group_training_reports_group FOREIGN KEY (group_id) REFERENCES learning_groups(id),
    CONSTRAINT fk_group_training_reports_subgroup FOREIGN KEY (subgroup_id) REFERENCES learning_groups(id),
    CONSTRAINT fk_group_training_reports_generated_by FOREIGN KEY (generated_by) REFERENCES users(id),
    UNIQUE KEY uk_group_training_reports_scope (contest_run_id, group_id, scope_key),
    INDEX idx_group_training_reports_group (group_id, subgroup_id, updated_at),
    INDEX idx_group_training_reports_run (contest_run_id, updated_at)
);

CREATE TABLE IF NOT EXISTS group_training_report_rows (
    id BIGINT PRIMARY KEY,
    report_id BIGINT NOT NULL,
    contest_id BIGINT NOT NULL,
    contest_run_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    subgroup_id BIGINT NULL,
    user_id BIGINT NOT NULL,
    account_snapshot VARCHAR(80) NOT NULL,
    display_name_snapshot VARCHAR(160),
    email_snapshot VARCHAR(160),
    contest_participant_id BIGINT NULL,
    participant_account_snapshot VARCHAR(80),
    participant_display_name_snapshot VARCHAR(160),
    participation_status VARCHAR(32) NOT NULL,
    submission_count INT NOT NULL DEFAULT 0,
    accepted_count INT NOT NULL DEFAULT 0,
    solved_count INT NOT NULL DEFAULT 0,
    penalty_minutes INT NOT NULL DEFAULT 0,
    first_accepted_at_millis BIGINT NULL,
    total_score DECIMAL(12,2) NULL,
    max_score DECIMAL(12,2) NULL,
    last_submission_at DATETIME(3) NULL,
    per_problem_json MEDIUMTEXT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    CONSTRAINT fk_group_training_rows_report FOREIGN KEY (report_id) REFERENCES group_training_reports(id),
    CONSTRAINT fk_group_training_rows_contest FOREIGN KEY (contest_id) REFERENCES contests(id),
    CONSTRAINT fk_group_training_rows_run FOREIGN KEY (contest_run_id) REFERENCES contest_runs(id),
    CONSTRAINT fk_group_training_rows_group FOREIGN KEY (group_id) REFERENCES learning_groups(id),
    CONSTRAINT fk_group_training_rows_subgroup FOREIGN KEY (subgroup_id) REFERENCES learning_groups(id),
    CONSTRAINT fk_group_training_rows_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_group_training_rows_participant FOREIGN KEY (contest_participant_id) REFERENCES contest_participants(id),
    INDEX idx_group_training_rows_report (report_id, account_snapshot),
    INDEX idx_group_training_rows_user (user_id, contest_run_id),
    INDEX idx_group_training_rows_scope (contest_run_id, group_id, subgroup_id)
);
