CREATE TABLE IF NOT EXISTS ai_problem_draft_agent_jobs (
    id BIGINT PRIMARY KEY,
    creator_user_id BIGINT NOT NULL,
    job_type VARCHAR(48) NOT NULL,
    status VARCHAR(32) NOT NULL,
    request_json JSON NOT NULL,
    progress_current INT NOT NULL DEFAULT 0,
    progress_total INT NOT NULL DEFAULT 0,
    progress_message VARCHAR(500) NULL,
    result_json JSON NULL,
    error_summary VARCHAR(1000) NULL,
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    cancelled_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    INDEX idx_agent_jobs_creator_status_created (creator_user_id, status, created_at),
    INDEX idx_agent_jobs_status_created (status, created_at),
    INDEX idx_agent_jobs_created (created_at)
);

CREATE TABLE IF NOT EXISTS ai_problem_draft_agent_job_items (
    id BIGINT PRIMARY KEY,
    job_id BIGINT NOT NULL,
    draft_id BIGINT NULL,
    item_index INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    algorithm_tags_json JSON NOT NULL,
    standard_solution_language VARCHAR(32) NOT NULL,
    cf_difficulty_score INT NOT NULL,
    latest_attempt_no INT NULL,
    latest_stage VARCHAR(64) NULL,
    latest_probe_verdict VARCHAR(64) NULL,
    error_summary VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    UNIQUE KEY uk_agent_job_items_job_index (job_id, item_index),
    INDEX idx_agent_job_items_job_id (job_id),
    INDEX idx_agent_job_items_status_created (status, created_at),
    INDEX idx_agent_job_items_draft_id (draft_id)
);

CREATE TABLE IF NOT EXISTS ai_problem_draft_agent_attempts (
    id BIGINT PRIMARY KEY,
    job_id BIGINT NOT NULL,
    job_item_id BIGINT NULL,
    draft_id BIGINT NULL,
    attempt_no INT NOT NULL,
    stage VARCHAR(64) NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    main_agent_summary VARCHAR(1000) NULL,
    validation_report_json JSON NULL,
    probe_verdict VARCHAR(64) NULL,
    probe_summary VARCHAR(1000) NULL,
    repair_plan_summary VARCHAR(1000) NULL,
    model VARCHAR(120) NULL,
    prompt_tokens BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    error_summary VARCHAR(1000) NULL,
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    UNIQUE KEY uk_problem_draft_agent_attempt_item_no (job_item_id, attempt_no),
    INDEX idx_problem_draft_agent_attempts_job (job_id),
    INDEX idx_problem_draft_agent_attempts_draft (draft_id),
    INDEX idx_problem_draft_agent_attempts_item (job_item_id)
);
