CREATE TABLE IF NOT EXISTS ai_problem_draft_generation_jobs (
    id BIGINT PRIMARY KEY,
    creator_user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    stage VARCHAR(64) NOT NULL,
    request_json JSON NOT NULL,
    topic_snapshot VARCHAR(255) NULL,
    progress_current INT NOT NULL DEFAULT 0,
    progress_total INT NOT NULL DEFAULT 1,
    progress_message VARCHAR(255) NULL,
    draft_id BIGINT NULL,
    error_code INT NULL,
    error_key VARCHAR(128) NULL,
    error_message VARCHAR(1000) NULL,
    lease_owner VARCHAR(128) NULL,
    lease_expires_at DATETIME(6) NULL,
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    INDEX idx_ai_problem_draft_jobs_status (status, created_at),
    INDEX idx_ai_problem_draft_jobs_creator (creator_user_id, created_at),
    INDEX idx_ai_problem_draft_jobs_draft (draft_id),
    INDEX idx_ai_problem_draft_jobs_lease (lease_expires_at)
);
