package com.aioj.next.contract.ai;

import com.aioj.next.contract.problem.TestCaseDto;

import java.time.Instant;
import java.util.List;

public record ProblemDraftResponse(
        Long id,
        String status,
        String title,
        String difficulty,
        String statement,
        String notes,
        String standardSolutionLanguage,
        String standardSolutionCode,
        String referenceSolutionLanguage,
        String referenceSolutionCode,
        String testcaseGeneratorPython,
        String stressTestcaseGeneratorPython,
        String generationPlan,
        List<String> tags,
        String validationStatus,
        List<String> validationErrors,
        List<TestCaseDto> testCases,
        Integer timeLimitMillis,
        Integer memoryLimitKb,
        Long importedProblemId,
        String model,
        long promptTokens,
        long completionTokens,
        Instant createdAt,
        Instant archivedAt,
        Instant deletedAt,
        Long deletedBy,
        Long refinedFromDraftId,
        String refineNote,
        String verificationStatus,
        String verificationReportJson,
        Integer repairAttemptCount,
        String lastRepairReason
) {
    public ProblemDraftResponse(
            Long id,
            String status,
            String title,
            String difficulty,
            String statement,
            String notes,
            String standardSolutionLanguage,
            String standardSolutionCode,
            String testcaseGeneratorPython,
            String generationPlan,
            List<String> tags,
            String validationStatus,
            List<String> validationErrors,
            List<TestCaseDto> testCases,
            Integer timeLimitMillis,
            Integer memoryLimitKb,
            Long importedProblemId,
            String model,
            long promptTokens,
            long completionTokens,
            Instant createdAt,
            Instant archivedAt,
            Instant deletedAt,
            Long deletedBy,
            Long refinedFromDraftId,
            String refineNote,
            String verificationStatus,
            String verificationReportJson,
            Integer repairAttemptCount,
            String lastRepairReason
    ) {
        this(id, status, title, difficulty, statement, notes, standardSolutionLanguage, standardSolutionCode,
                null, null, testcaseGeneratorPython, null, generationPlan, tags, validationStatus, validationErrors,
                testCases, timeLimitMillis, memoryLimitKb, importedProblemId, model, promptTokens, completionTokens,
                createdAt, archivedAt, deletedAt, deletedBy, refinedFromDraftId, refineNote, verificationStatus,
                verificationReportJson, repairAttemptCount, lastRepairReason);
    }

    public ProblemDraftResponse(
            Long id,
            String status,
            String title,
            String difficulty,
            String statement,
            String notes,
            String standardSolutionLanguage,
            String standardSolutionCode,
            String referenceSolutionLanguage,
            String referenceSolutionCode,
            String testcaseGeneratorPython,
            String generationPlan,
            List<String> tags,
            String validationStatus,
            List<String> validationErrors,
            List<TestCaseDto> testCases,
            Integer timeLimitMillis,
            Integer memoryLimitKb,
            Long importedProblemId,
            String model,
            long promptTokens,
            long completionTokens,
            Instant createdAt,
            Instant archivedAt,
            Instant deletedAt,
            Long deletedBy,
            Long refinedFromDraftId,
            String refineNote
    ) {
        this(id, status, title, difficulty, statement, notes, standardSolutionLanguage, standardSolutionCode,
                referenceSolutionLanguage, referenceSolutionCode, testcaseGeneratorPython, null, generationPlan, tags,
                validationStatus, validationErrors, testCases, timeLimitMillis, memoryLimitKb, importedProblemId,
                model, promptTokens, completionTokens, createdAt, archivedAt, deletedAt, deletedBy,
                refinedFromDraftId, refineNote, "NOT_RUN", null, 0, null);
    }

    public ProblemDraftResponse(
            Long id,
            String status,
            String title,
            String difficulty,
            String statement,
            String notes,
            String standardSolutionLanguage,
            String standardSolutionCode,
            String referenceSolutionLanguage,
            String referenceSolutionCode,
            String testcaseGeneratorPython,
            String stressTestcaseGeneratorPython,
            String generationPlan,
            List<String> tags,
            String validationStatus,
            List<String> validationErrors,
            List<TestCaseDto> testCases,
            Integer timeLimitMillis,
            Integer memoryLimitKb,
            Long importedProblemId,
            String model,
            long promptTokens,
            long completionTokens,
            Instant createdAt,
            Instant archivedAt,
            Instant deletedAt,
            Long deletedBy,
            Long refinedFromDraftId,
            String refineNote
    ) {
        this(id, status, title, difficulty, statement, notes, standardSolutionLanguage, standardSolutionCode,
                referenceSolutionLanguage, referenceSolutionCode, testcaseGeneratorPython, stressTestcaseGeneratorPython, generationPlan, tags,
                validationStatus, validationErrors, testCases, timeLimitMillis, memoryLimitKb, importedProblemId,
                model, promptTokens, completionTokens, createdAt, archivedAt, deletedAt, deletedBy,
                refinedFromDraftId, refineNote, "NOT_RUN", null, 0, null);
    }

    public ProblemDraftResponse(
            Long id,
            String status,
            String title,
            String difficulty,
            String statement,
            String notes,
            String standardSolutionLanguage,
            String standardSolutionCode,
            String testcaseGeneratorPython,
            String generationPlan,
            List<String> tags,
            String validationStatus,
            List<String> validationErrors,
            List<TestCaseDto> testCases,
            Integer timeLimitMillis,
            Integer memoryLimitKb,
            Long importedProblemId,
            String model,
            long promptTokens,
            long completionTokens,
            Instant createdAt,
            Instant archivedAt,
            Instant deletedAt,
            Long deletedBy,
            Long refinedFromDraftId,
            String refineNote
    ) {
        this(id, status, title, difficulty, statement, notes, standardSolutionLanguage, standardSolutionCode,
                null, null, testcaseGeneratorPython, null, generationPlan, tags, validationStatus, validationErrors, testCases,
                timeLimitMillis, memoryLimitKb, importedProblemId, model, promptTokens, completionTokens, createdAt,
                archivedAt, deletedAt, deletedBy, refinedFromDraftId, refineNote, "NOT_RUN", null, 0, null);
    }
}
