package com.aioj.next.contract.operation;

public enum OperationJobType {
    EXPORT_SCOREBOARD,
    EXPORT_SUBMISSIONS,
    EXPORT_PLAGIARISM_REPORT,
    RUN_PLAGIARISM_CHECK,
    GENERATE_SCOREBOARD_TIMELINE,
    GENERATE_CONTEST_POSTMORTEM,
    GENERATE_STUDENT_POSTMORTEM,
    BATCH_GENERATE_STUDENT_POSTMORTEMS
}
